### ISSUE TITLE
⚡ Release v1.6.0

### ISSUE THREAD

**Issue by in4s** [in4s/utest#12]
- [ ] ** Update RSR (optional)
- [ ] ** if the branch 1.6 does not exist
    - [ ] git checkout PREVIEWS_BRANCH_NAME
    - [ ] git pull
    - [ ] create the branch 1.6
    - [ ] git checkout the branch 1.6
    - [ ] git push
    - [ ] !!! If the branch has the highest number, set it as the default branch on [Github](https://github.com/in4s/utest/settings/branches)
- [ ] git checkout the branch 1.6
- [x] git pull
- [x] git checkout -b Release_v1.6.0_#12
- [x] ** check PSR by running php-cs-fixer
    - [x] php-cs-fixer fix .
    - [ ] if files were changed
        - [ ] git add .
        - [ ] git commit -m "php-cs-fixed"
- [x] Fix the current version number in files:
    - [x] In README.md
    - [x] In composer.json
- [x] git add . , git commit -m "⚡ Release v1.6.0 close #12"
- [x] (C*rmr) By process IV Create pull request "⚡ Release v1.6.0 close #12"
------
- [x] !!!!!!!!!!!!!!!!!!!!!! (cRM*R) Review pull request, Merge it, !!!!!!!!!!!!!! swapping title and description, Remove remote branch
- [x] click and save https://github.com/in4s/utest/releases/new?tag=v1.6.0&target=1.6
- [x] Increase the version number in local data.js
- [x] Remove local branch
- [ ] click and save https://github.com/in4s/utest/issues/new/?assignees=in4s&labels=test,canProceed,Urgent&title=☑+v1.6.0+on+m&body=-+%5B+%5D+Pin+this+issue%3B+Pin+it+to+the+left%0D%0A-+%5B+%5D+Run+the+test+and+complete+it%0D%0A-+%5B+%5D+Unpin+this+issue+after+closing+it
- [ ] Pin this test issue; Pin it to the left
- [x] Close milestone with current version name
- [x] Unpin this issue
