### ISSUE TITLE
⚡ Release v1.7.0

### ISSUE THREAD

**Issue by in4s** [in4s/utest#28]
- [x] git checkout main
- [x] git pull
- [x] git checkout -b Release_v1.7.0_#28
- [x] ** check PSR by running php-cs-fixer
    - [x] php-cs-fixer fix .
    - [ ] if files were changed
        - [ ] git add .
        - [ ] git commit -m "php-cs-fixed"
- [x] Fix the current version number in files:
    - [x] In README.md
    - [x] In composer.json
- [x] git add . , git commit -m "⚡ Release v1.7.0 close #28"
- [x] (C*rmr) By process IV Create pull request "⚡ Release v1.7.0 close #28"
------
- [x] !!!!!!!!!!!!!!!!!!!!!! (cRM*R) Review pull request, Merge it, !!!!!!!!!!!!!! swapping title and description, Remove remote branch
- [x] click and save https://github.com/in4s/utest/releases/new?tag=v1.7.0&target=1.7
- [x] Increase the version number in local data.js
- [x] Remove local branch
- [ ] click and save https://github.com/in4s/utest/issues/new/?assignees=in4s&labels=test,canProceed,Urgent&title=☑+v1.7.0+on+m&body=-+%5B+%5D+Pin+this+issue%3B+Pin+it+to+the+left%0D%0A-+%5B+%5D+Run+the+test+and+complete+it%0D%0A-+%5B+%5D+Unpin+this+issue+after+closing+it
- [ ] Pin this test issue; Pin it to the left
- [x] Close milestone with current version name
- [x] Unpin this issue
